site_name: Robotics Portfolio
site_url: https://zackgald1.github.io/robotics-portfolio
repo_url: https://github.com/zackgald1/robotics-portfolio
edit_uri: edit/main/docs/

theme:
  name: material
  logo: images/favicon.png
  favicon: images/favicon.png
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - content.code.copy
    - toc.integrate

nav:
  - ğŸ  Home: index.md
  - ğŸ’¼ Projects:
      - ğŸ  Overview: projects/index.md
      - ğŸ§µ String Machine: projects/string-machine.md
      - ğŸ¯ Object Tracker: projects/object-tracker.md
      - ğŸ¤– Pick-and-Place: projects/pick-and-place.md
  - ğŸ‘¶ Early Life: Earlylife.md
  - ğŸ“„ Resume: resume.md
  - ğŸ“¬ Contact: contact.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zackgald1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zack-gald-52a765253
